import type { TreeItem, Course } from '@/types';

export const CONTENT_FOREST = 1;

const nowIso = (): string => new Date().toISOString();

type SampleData = {
  trees: TreeItem[];
  courses: Course[];
};

// English samples
const enSamples: SampleData = {
  trees: [
    {
      id: 1,
      forestId: CONTENT_FOREST,
      parentId: null,
      position: 0,
      path: '/1/',
      name: 'Banking',
      type: 'tree',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Branches
    {
      id: 2,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 0,
      path: '/1/2/',
      name: 'Accounts',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 3,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 1,
      path: '/1/3/',
      name: 'Credits',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 4,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 2,
      path: '/1/4/',
      name: 'Payments',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 5,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 3,
      path: '/1/5/',
      name: 'Risks',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Accounts
    {
      id: 6,
      forestId: CONTENT_FOREST,
      parentId: 2,
      position: 0,
      path: '/1/2/6/',
      name: 'Checking Accounts',
      type: 'leaf',
      objectId: 'course-checking-accounts-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 7,
      forestId: CONTENT_FOREST,
      parentId: 2,
      position: 1,
      path: '/1/2/7/',
      name: 'Savings Accounts',
      type: 'leaf',
      objectId: 'course-savings-accounts-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Credits
    {
      id: 8,
      forestId: CONTENT_FOREST,
      parentId: 3,
      position: 0,
      path: '/1/3/8/',
      name: 'Personal Loans',
      type: 'leaf',
      objectId: 'course-personal-loans-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 9,
      forestId: CONTENT_FOREST,
      parentId: 3,
      position: 1,
      path: '/1/3/9/',
      name: 'Credit Cards',
      type: 'leaf',
      objectId: 'course-credit-cards-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Payments
    {
      id: 10,
      forestId: CONTENT_FOREST,
      parentId: 4,
      position: 0,
      path: '/1/4/10/',
      name: 'Wire Transfers',
      type: 'leaf',
      objectId: 'course-wire-transfers-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Risks
    {
      id: 11,
      forestId: CONTENT_FOREST,
      parentId: 5,
      position: 0,
      path: '/1/5/11/',
      name: 'Credit Risk',
      type: 'leaf',
      objectId: 'course-credit-risk-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 12,
      forestId: CONTENT_FOREST,
      parentId: 5,
      position: 1,
      path: '/1/5/12/',
      name: 'AML / KYC',
      type: 'leaf',
      objectId: 'course-aml-kyc-en',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
  ],
  courses: [
    {
      id: 'course-checking-accounts-en',
      author: 'Banking Academy',
      fullName: 'Checking Accounts Fundamentals',
      description: 'Learn the basics of checking accounts, including opening, managing, and understanding account features.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-savings-accounts-en',
      author: 'Banking Academy',
      fullName: 'Savings Accounts Guide',
      description: 'Comprehensive guide to savings accounts, interest rates, and savings strategies.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-personal-loans-en',
      author: 'Banking Academy',
      fullName: 'Personal Loans Overview',
      description: 'Understanding personal loans, application process, and repayment options.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-credit-cards-en',
      author: 'Banking Academy',
      fullName: 'Credit Cards Essentials',
      description: 'Master credit card features, benefits, and responsible usage.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-wire-transfers-en',
      author: 'Banking Academy',
      fullName: 'Wire Transfers and International Payments',
      description: 'Learn about wire transfers, international payments, and transfer procedures.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-credit-risk-en',
      author: 'Banking Academy',
      fullName: 'Credit Risk Management',
      description: 'Fundamentals of credit risk assessment, analysis, and mitigation strategies.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-aml-kyc-en',
      author: 'Banking Academy',
      fullName: 'AML and KYC Compliance',
      description: 'Anti-Money Laundering and Know Your Customer procedures and best practices.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
  ],
};

// Russian samples
const ruSamples: SampleData = {
  trees: [
    {
      id: 1,
      forestId: CONTENT_FOREST,
      parentId: null,
      position: 0,
      path: '/1/',
      name: 'Банковское дело',
      type: 'tree',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Branches
    {
      id: 2,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 0,
      path: '/1/2/',
      name: 'Счета',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 3,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 1,
      path: '/1/3/',
      name: 'Кредиты',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 4,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 2,
      path: '/1/4/',
      name: 'Платежи',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 5,
      forestId: CONTENT_FOREST,
      parentId: 1,
      position: 3,
      path: '/1/5/',
      name: 'Риски',
      type: 'branch',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Accounts
    {
      id: 6,
      forestId: CONTENT_FOREST,
      parentId: 2,
      position: 0,
      path: '/1/2/6/',
      name: 'Текущие счета',
      type: 'leaf',
      objectId: 'course-checking-accounts-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 7,
      forestId: CONTENT_FOREST,
      parentId: 2,
      position: 1,
      path: '/1/2/7/',
      name: 'Сберегательные счета',
      type: 'leaf',
      objectId: 'course-savings-accounts-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Credits
    {
      id: 8,
      forestId: CONTENT_FOREST,
      parentId: 3,
      position: 0,
      path: '/1/3/8/',
      name: 'Потребительские кредиты',
      type: 'leaf',
      objectId: 'course-personal-loans-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 9,
      forestId: CONTENT_FOREST,
      parentId: 3,
      position: 1,
      path: '/1/3/9/',
      name: 'Кредитные карты',
      type: 'leaf',
      objectId: 'course-credit-cards-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Payments
    {
      id: 10,
      forestId: CONTENT_FOREST,
      parentId: 4,
      position: 0,
      path: '/1/4/10/',
      name: 'Банковские переводы',
      type: 'leaf',
      objectId: 'course-wire-transfers-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    // Leaves under Risks
    {
      id: 11,
      forestId: CONTENT_FOREST,
      parentId: 5,
      position: 0,
      path: '/1/5/11/',
      name: 'Кредитный риск',
      type: 'leaf',
      objectId: 'course-credit-risk-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 12,
      forestId: CONTENT_FOREST,
      parentId: 5,
      position: 1,
      path: '/1/5/12/',
      name: 'ПОД / KYC',
      type: 'leaf',
      objectId: 'course-aml-kyc-ru',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
  ],
  courses: [
    {
      id: 'course-checking-accounts-ru',
      author: 'Банковская Академия',
      fullName: 'Основы текущих счетов',
      description: 'Изучите основы текущих счетов, включая открытие, управление и понимание функций счета.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-savings-accounts-ru',
      author: 'Банковская Академия',
      fullName: 'Руководство по сберегательным счетам',
      description: 'Подробное руководство по сберегательным счетам, процентным ставкам и стратегиям сбережений.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-personal-loans-ru',
      author: 'Банковская Академия',
      fullName: 'Обзор потребительских кредитов',
      description: 'Понимание потребительских кредитов, процесса подачи заявки и вариантов погашения.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-credit-cards-ru',
      author: 'Банковская Академия',
      fullName: 'Основы кредитных карт',
      description: 'Освойте функции кредитных карт, преимущества и ответственное использование.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-wire-transfers-ru',
      author: 'Банковская Академия',
      fullName: 'Банковские переводы и международные платежи',
      description: 'Узнайте о банковских переводах, международных платежах и процедурах перевода.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-credit-risk-ru',
      author: 'Банковская Академия',
      fullName: 'Управление кредитным риском',
      description: 'Основы оценки кредитного риска, анализа и стратегий снижения рисков.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
    {
      id: 'course-aml-kyc-ru',
      author: 'Банковская Академия',
      fullName: 'Соответствие требованиям ПОД и KYC',
      description: 'Процедуры противодействия отмыванию денег и идентификации клиентов, а также лучшие практики.',
      createdAt: nowIso(),
      updatedAt: nowIso(),
      deletedAt: null,
    },
  ],
};

export function getSamples(locale: 'en' | 'ru'): SampleData {
  return locale === 'ru' ? ruSamples : enSamples;
}

export function getSampleTrees(locale: 'en' | 'ru'): TreeItem[] {
  return getSamples(locale).trees;
}

export function getSampleCourses(locale: 'en' | 'ru'): Course[] {
  return getSamples(locale).courses;
}

